version: '3.7'

services:
  db:
    container_name: 'users_db'
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    
